version: '3.8'

services:
  web:
    build: .
    container_name: toolsite_web
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      FLASK_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "345919970120xc"
    networks:
      - app_net

  redis:
    image: redis:7
    container_name: toolsite_redis
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 345919970120xc
    networks:
      - app_net
  nginx:
    image: nginx:stable
    container_name: toolsite_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # 关键修改：挂载到 conf.d 目录下的 default.conf，而非主配置文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  
    depends_on:
      - web
    networks:
      - app_net

networks:
  app_net:

volumes:
  redis_data:

